repos:
-   repo: https://github.com/PyCQA/pylint
    rev: v2.16.2
    hooks:
    -   id: pylint
        args:
        -   --disable=import-error,import-outside-toplevel, missing-module-docstring, missing-class-docstring, too-few-public-methods, missing-function-docstring, fixme
        -   --ignore-paths=^app/migrations/.*|tests/app/.*$
        -   --max-line-length=120
        -   --good-names=a,b,i,j,k,l,r,x,y,z,u,v,w,p,q,n,ch,fp,wb,ws
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.217
    hooks:
    -   id: ruff
        # Respect `exclude` and `extend-exclude` settings.
        args:
        -   --force-exclude
        -   --line-length=120
        -   --format=github
        -   --target-version=py39
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: html
    -   id: trailing-whitespace
        exclude: html
    -   id: check-ast
    -   id: check-case-conflict
    -   id: pretty-format-json
        args:
        -   --autofix
        -   --indent=4
    -   id: name-tests-test
        args:
        -   --pytest-test-first
    -   id: fix-byte-order-marker
    -   id: debug-statements
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args:
        -   --line-length=120
-   repo: https://github.com/myint/autoflake.git
    rev: b330072a26bb13aea8843f8083cee5332d71f78f
    hooks:
    -   id: autoflake
        args:
        -   --in-place
        -   --remove-all-unused-imports
        -   --remove-unused-variable
        -   --expand-star-imports
        -   --ignore-init-module-imports
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0    # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        args:
        -   --max-line-length=120
        -   --max-complexity=10
        -   --ignore=A003
        additional_dependencies:
        -   flake8-alfred
        -   flake8-blind-except
        -   flake8-builtins
-   repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
    -   id: dockerfilelint
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.7.0
    hooks:
    -   id: pretty-format-yaml
        args: [--autofix, --indent, '4']
-   repo: https://github.com/myint/docformatter
    rev: v1.5.1
    hooks:
    -   id: docformatter
        args:
        -   --wrap-descriptions=120
        -   --wrap-summaries=120
        -   --close-quotes-on-newline
        -   --pre-summary-newline
        -   --in-place
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
    -   id: markdownlint
    -   id: markdownlint-fix
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.0
    hooks:
    -   id: python-use-type-annotations
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: [--profile, black]
